### ISSUE TITLE
Locked character sheet skill totals don't match the unlocked sheet or edited values

### ISSUE THREAD

**Issue by alexanderjgray** [HavlockV/CoC7-FoundryVTT#1289]
Am running the latest Foundry version 10 Build 288, and the latest Call of Cthulhu version 0.9.2.
Bug persists regardless of modules.

## Description.

Some skills added by both the example and custom setups have differing values depending on whether the sheet is locked or unlocked.
It's specific to skills added by setups and doesn't seem to apply to manually added skills. Renaming the skills fixes the "issue." Also seems specific to: Art/Craft Any, Pilot Any, Science Any and Survival Any. 

Adding a new skill to the sheet can also result in changes to bugged skills, for instance after adding a second Art/Craft Any, both Art/Crafts work properly but the Survival Any became bugged and the bugged values of Science Any and Pilot Any changed from 10 to 5.

Not big issue given how easy it is to fix but has caused me and players some confusion.

## Expected Behavior.

Art/Craft Any should be 5 not 10
Pilot Any should be 1 not 10
Science Any should be 1 not 10

Edited total values in skills tab should persist into locked sheet.
Making changes in the development tab should be totalled in the value column and show in the skill tab.

## Actual Behavior.

Skill values change when locked and unlocked. There's a unlocked value and a locked value.
Editing the value of bugged skills when unlocked does not persist when locked.
Changes made in the development tab to bugged skills do not total.

## Screenshots.

![locked-sheet](https://user-images.githubusercontent.com/85560374/201163337-04cee0a1-b21e-428f-a5f5-1a650104667f.jpg)
![unlocked-sheet](https://user-images.githubusercontent.com/85560374/201163369-4f4c3be1-2554-4694-84ac-ffd2686cac4e.jpg)
![development-sheet](https://user-images.githubusercontent.com/85560374/201163391-6d2ff8f0-a724-4f37-91cd-5fbab63abb44.jpg)
After adding another skill note the totals of Survival, Pilot and Science have changed:
![after-changes-development](https://user-images.githubusercontent.com/85560374/201165976-838cdbe3-1e67-4507-92d8-3068435705bc.jpg)
![after-changes-skills](https://user-images.githubusercontent.com/85560374/201165998-9c1e9f14-f1c4-4ec0-8418-c1315e017274.jpg)

**Comment by kwitczak** [comment]
Thanks for reporting @alexanderjgray. I was able to reproduce it.
It seems that the problem is related to using **the same name** in specialised groups. It doesn't matter from which specialisation group skills come from, or if they are coming from compendium or not.

I provided a couple of examples below.

**Example 1:** Here, values are unique in both locked or unlocked mode.
<img width="672" alt="Screenshot 2023-03-10 at 19 27 04" src="https://user-images.githubusercontent.com/8782549/224383733-81e9211d-4859-4d02-9ca1-03ed9fae81a2.png">
<img width="673" alt="Screenshot 2023-03-10 at 19 27 14" src="https://user-images.githubusercontent.com/8782549/224383750-14bef634-0602-42c8-9878-69f9e52271c0.png">

**Example 2:** Almost identical example but using only "Any" as a value creates a problem.
<img width="682" alt="Screenshot 2023-03-10 at 19 28 19" src="https://user-images.githubusercontent.com/8782549/224383746-e1e2f17c-e871-4be5-aa80-90ccc07f9927.png">
<img width="673" alt="Screenshot 2023-03-10 at 19 28 12" src="https://user-images.githubusercontent.com/8782549/224383711-ccbfca67-8cf4-4bc6-88cf-5cc6fe2799f1.png">

**Example 3:** Minimal repro
<img width="677" alt="Screenshot 2023-03-10 at 19 31 02" src="https://user-images.githubusercontent.com/8782549/224383738-09ea5480-c3ee-482b-812b-a586d6671838.png">
<img width="673" alt="Screenshot 2023-03-10 at 19 30 55" src="https://user-images.githubusercontent.com/8782549/224383742-c3207723-06c5-41ad-b4ea-ab2c9e723865.png">

I'll work on the fix.
